### PR TITLE
Update Dad.kt

### PR DESCRIPTION
**Pull request by Proper9**

### CODE REVIEW

**Review by grant-mullinax — APPROVED** [review]
ok fine b

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Comment by Proper9** [comment]
n word

**Pull request merged**
